# Aufgabe 6 (Analyse von Stromtarif-Angeboten für Endkunden)

**In dieser Aufgabe sollen Neukunden-Angebotspreise für Endkunden in verschiedenen bayerischen Städten aus dem Jahr 2024 analysiert werden, wie sie beispielsweise auf Preisvergleichsportalen zu finden sind. Es ist pro Tag und Stadt eine JSON-Datei gegeben, in der bis zu 20 Tarifangebote aufgeführt sind, die an diesem Tag in dieser Stadt am günstigsten waren (Sortierung nach `Preis im 1. Jahr`) Die angebotenen Tarife beziehen sich jeweils auf einen jährlichen Gesamtverbrauch von 4000 kWh/Jahr. \
 a) Führen Sie die gegebenen Preisvergleichdaten in einem DataFrame namens `df_cust` zusammen. Exportieren Sie diesen als CSV-Datei namens `prices_customers.csv` und
 laden Sie diese mit Ihrer Abgabe auf Moodle hoch. Verwerfen Sie bitte zur Minimierung der Dateigröße alle Spalten, die im weiteren Verlauf nicht mehr verwendet werden. Kommentieren Sie nun den Code zur Datensatzgenerierung aus und lesen Sie die CSV-Datei in den DataFrame `df_cust` erneut aus dieser Datei ein. \
 b) Bereiten Sie die Daten auf die weitere Analyse vor, indem Sie geeignete Datentransformations- und-bereinigungsschritte durchführen.**

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import openmeteo_requests
import requests_cache
from retry_requests import retry
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import HuberRegressor
import glob

In [2]:
'''def join_json_files_to_dataframe(base_folder):
    # Initialize an empty list to store data from all JSON files
    data_list = []
    
    # Recursively find all JSON files in the base folder
    for file_path in glob.glob(os.path.join(base_folder, '**', '*.json'), recursive=True):
        try:
            # Read each JSON file into a DataFrame and append to the list
            data = pd.read_json(file_path, lines=True)  # Use lines=True for JSONL files
            data_list.append(data)
        except ValueError as e:
            print(f"Error reading {file_path}: {e}")
    
    # Concatenate all DataFrames into a single DataFrame
    if data_list:
        combined_df = pd.concat(data_list, ignore_index=True)
        return combined_df
    else:
        print("No JSON files found or all files were invalid.")
        return pd.DataFrame()  # Return an empty DataFrame if no data

# Example usage
base_folder = "DAT-WS2425-Projektarbeit/DAT-WS2425-Projektarbeit/Daten/Endkundenpreise"
df_cust = join_json_files_to_dataframe(base_folder)

# Display the resulting DataFrame
df_cust'''

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,"{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '..."
1,"{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '..."
2,"{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '..."
3,"{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '..."
4,"{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12812,"{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '..."
12813,"{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '..."
12814,"{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '..."
12815,"{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '..."
12816,"{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '..."

In [3]:
#df_cust.to_csv("df_cust.csv", encoding="utf-8", index=False)

In [4]:
'''df_cust = pd.read_csv('df_cust.csv')
df_cust'''

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,"{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '...","{'Postleitzahl': '80331', 'Jahresverbrauch': '..."
1,"{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '...","{'Postleitzahl': '83024', 'Jahresverbrauch': '..."
2,"{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '...","{'Postleitzahl': '84028', 'Jahresverbrauch': '..."
3,"{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '...","{'Postleitzahl': '86150', 'Jahresverbrauch': '..."
4,"{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '...","{'Postleitzahl': '89233', 'Jahresverbrauch': '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12812,"{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '...","{'Postleitzahl': '95478', 'Jahresverbrauch': '..."
12813,"{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '...","{'Postleitzahl': '95643', 'Jahresverbrauch': '..."
12814,"{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '...","{'Postleitzahl': '96050', 'Jahresverbrauch': '..."
12815,"{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '...","{'Postleitzahl': '96450', 'Jahresverbrauch': '..."
12816,"{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '...","{'Postleitzahl': '97070', 'Jahresverbrauch': '..."

In [5]:
'''import ast
for col in df_cust.columns:
    df_cust[col] = df_cust[col].apply(ast.literal_eval)

combined_df = pd.DataFrame()

for column in df_cust.columns:
    temp_df = pd.json_normalize(df_cust[column])
    combined_df = pd.concat([combined_df, temp_df], ignore_index=True)
    
combined_df'''

,Postleitzahl,Jahresverbrauch,Abschlagszahlung,Grundpreis,Arbeitspreis,Preisgarantie,Vertragslaufzeit,Verlängerung,Kündigungsfrist,Preis im 1. Jahr*,...,Neukundenbonus,Sofortbonus,Preis im 1. Jahr,Grundpreisrabatt:,Arbeitspreisrabatt,Grundpreisrabatt,Blitzbonus,Abschlagsrabatt,Zusätzlicher Aktionsbonus,Winterprämie
0,80331,4.000 kWh,monatlich,"14,40 €/Monat (172,86 €/Jahr)","19,61 Cent/kWh",1 Monat Preisfixierung,1 Monat,1 Monat,1 Monat,"79,77 €/Monat",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,83024,4.000 kWh,monatlich,"14,40 €/Monat (172,86 €/Jahr)","19,74 Cent/kWh",1 Monat Preisfixierung,1 Monat,1 Monat,1 Monat,"80,20 €/Monat",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,84028,4.000 kWh,monatlich,"14,40 €/Monat (172,86 €/Jahr)","20,32 Cent/kWh",1 Monat Preisfixierung,1 Monat,1 Monat,1 Monat,"82,14 €/Monat",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,86150,4.000 kWh,monatlich,"14,40 €/Monat (172,86 €/Jahr)","19,19 Cent/kWh",1 Monat Preisfixierung,1 Monat,1 Monat,1 Monat,"78,37 €/Monat",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,89233,4.000 kWh,monatlich,"14,40 €/Monat (172,86 €/Jahr)","22,02 Cent/kWh",1 Monat Preisfixierung,1 Monat,1 Monat,1 Monat,"87,80 €/Monat",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256335,95478,4.000 kWh,monatlich,"14,78 €/Monat (177,31 €/Jahr)","31,43 Cent/kWh",12 Monate Nettopreisgarantie,12 Monate,4 Wochen,4 Wochen,NaN,...,214 €,55 €,"97,13 €/Monat",NaN,NaN,NaN,NaN,NaN,NaN,NaN
256336,95643,4.000 kWh,monatlich,"15,57 €/Monat (186,83 €/Jahr)","33,74 Cent/kWh",12 Monate Nettopreisgarantie,12 Monate,1 Monat,1 Monat,NaN,...,230 €,NaN,"108,84 €/Monat",NaN,NaN,NaN,NaN,NaN,NaN,NaN
256337,96050,4.000 kWh,monatlich,"14,31 €/Monat (171,76 €/Jahr)","31,73 Cent/kWh",12 Monate Nettopreisgarantie,12 Monate,4 Wochen,4 Wochen,NaN,...,216 €,58 €,"97,25 €/Monat",NaN,NaN,NaN,NaN,NaN,NaN,NaN
256338,96450,4.000 kWh,monatlich,"15,35 €/Monat (184,22 €/Jahr)","31,84 Cent/kWh",12 Monate Nettopreisgarantie,12 Monate,4 Wochen,4 Wochen,NaN,...,218 €,55 €,"98,74 €/Monat",NaN,NaN,NaN,NaN,NaN,NaN,NaN
256339,97070,4.000 kWh,monatlich,"18,04 €/Monat (216,46 €/Jahr)","26,82 Cent/kWh",12 Monate Preisfixierung,12 Monate,1 Monat,1 Monat,NaN,...,100 €,140 €,"87,45 €/Monat",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#combined_df.to_csv("final_df.csv", encoding="utf-8", index=False)

In [7]:
final_df = pd.read_csv('final_df.csv', low_memory=False)
final_df

,Postleitzahl,Jahresverbrauch,Abschlagszahlung,Grundpreis,Arbeitspreis,Preisgarantie,Vertragslaufzeit,Verlängerung,Kündigungsfrist,Preis im 1. Jahr*,...,Neukundenbonus,Sofortbonus,Preis im 1. Jahr,Grundpreisrabatt:,Arbeitspreisrabatt,Grundpreisrabatt,Blitzbonus,Abschlagsrabatt,Zusätzlicher Aktionsbonus,Winterprämie
0,80331.0,4.000 kWh,monatlich,"14,40 €/Monat (172,86 €/Jahr)","19,61 Cent/kWh",1 Monat Preisfixierung,1 Monat,1 Monat,1 Monat,"79,77 €/Monat",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,83024.0,4.000 kWh,monatlich,"14,40 €/Monat (172,86 €/Jahr)","19,74 Cent/kWh",1 Monat Preisfixierung,1 Monat,1 Monat,1 Monat,"80,20 €/Monat",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,84028.0,4.000 kWh,monatlich,"14,40 €/Monat (172,86 €/Jahr)","20,32 Cent/kWh",1 Monat Preisfixierung,1 Monat,1 Monat,1 Monat,"82,14 €/Monat",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,86150.0,4.000 kWh,monatlich,"14,40 €/Monat (172,86 €/Jahr)","19,19 Cent/kWh",1 Monat Preisfixierung,1 Monat,1 Monat,1 Monat,"78,37 €/Monat",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,89233.0,4.000 kWh,monatlich,"14,40 €/Monat (172,86 €/Jahr)","22,02 Cent/kWh",1 Monat Preisfixierung,1 Monat,1 Monat,1 Monat,"87,80 €/Monat",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256335,95478.0,4.000 kWh,monatlich,"14,78 €/Monat (177,31 €/Jahr)","31,43 Cent/kWh",12 Monate Nettopreisgarantie,12 Monate,4 Wochen,4 Wochen,NaN,...,214 €,55 €,"97,13 €/Monat",NaN,NaN,NaN,NaN,NaN,NaN,NaN
256336,95643.0,4.000 kWh,monatlich,"15,57 €/Monat (186,83 €/Jahr)","33,74 Cent/kWh",12 Monate Nettopreisgarantie,12 Monate,1 Monat,1 Monat,NaN,...,230 €,NaN,"108,84 €/Monat",NaN,NaN,NaN,NaN,NaN,NaN,NaN
256337,96050.0,4.000 kWh,monatlich,"14,31 €/Monat (171,76 €/Jahr)","31,73 Cent/kWh",12 Monate Nettopreisgarantie,12 Monate,4 Wochen,4 Wochen,NaN,...,216 €,58 €,"97,25 €/Monat",NaN,NaN,NaN,NaN,NaN,NaN,NaN
256338,96450.0,4.000 kWh,monatlich,"15,35 €/Monat (184,22 €/Jahr)","31,84 Cent/kWh",12 Monate Nettopreisgarantie,12 Monate,4 Wochen,4 Wochen,NaN,...,218 €,55 €,"98,74 €/Monat",NaN,NaN,NaN,NaN,NaN,NaN,NaN
256339,97070.0,4.000 kWh,monatlich,"18,04 €/Monat (216,46 €/Jahr)","26,82 Cent/kWh",12 Monate Preisfixierung,12 Monate,1 Monat,1 Monat,NaN,...,100 €,140 €,"87,45 €/Monat",NaN,NaN,NaN,NaN,NaN,NaN,NaN

**c) Wie viele verschiedene Tarife wurden insgesamt angeboten?**

In [8]:
print(len(final_df['Tarif'].unique()))

112

**Zu wie vielen Tagen sind pro Stadt Daten vorhanden?**

In [9]:
final_df.groupby('Stadt').count()/20

,Postleitzahl,Jahresverbrauch,Abschlagszahlung,Grundpreis,Arbeitspreis,Preisgarantie,Vertragslaufzeit,Verlängerung,Kündigungsfrist,Preis im 1. Jahr*,...,Neukundenbonus,Sofortbonus,Preis im 1. Jahr,Grundpreisrabatt:,Arbeitspreisrabatt,Grundpreisrabatt,Blitzbonus,Abschlagsrabatt,Zusätzlicher Aktionsbonus,Winterprämie
Stadt,,,,,,,,,,,,,,,,,,,,,
Amberg,321.95,321.95,321.95,321.95,321.95,321.95,321.95,321.95,321.95,78.45,...,234.60,206.65,243.50,2.45,26.05,9.50,11.45,2.80,1.50,0.90
Ansbach,319.05,319.05,319.05,319.05,319.05,319.05,319.05,319.05,319.05,81.95,...,228.40,192.95,237.10,2.25,26.90,8.70,12.80,2.15,0.90,1.10
Aschaffenburg,319.65,319.65,319.65,319.65,319.65,319.65,319.65,319.65,319.65,72.70,...,238.60,203.55,246.95,0.90,26.40,4.50,12.65,2.00,0.75,1.45
Augsburg,320.55,320.55,320.55,320.55,320.55,320.55,320.55,320.55,320.55,79.75,...,233.45,208.40,240.80,1.65,24.90,9.50,11.15,1.85,0.70,1.30
Bamberg,319.15,319.15,319.15,319.15,319.15,319.15,319.15,319.15,319.15,82.05,...,228.30,198.15,237.10,2.25,22.90,4.60,12.25,2.05,0.30,1.30
Bayreuth,318.75,318.75,318.75,318.75,318.75,318.75,318.75,318.75,318.75,81.30,...,229.25,201.85,237.45,2.90,30.00,10.55,11.55,1.85,0.60,0.85
Beilngries,320.60,320.60,320.60,320.60,320.60,320.60,320.60,320.60,320.60,82.50,...,230.75,199.85,238.10,2.50,19.55,5.95,10.55,2.95,0.70,1.85
Burglengenfeld,320.35,320.35,320.35,320.35,320.35,320.35,320.35,320.35,320.35,80.55,...,234.10,204.10,239.80,3.10,20.05,6.20,9.45,2.75,0.65,1.75
Cham,317.70,317.70,317.70,317.70,317.70,317.70,317.70,317.70,317.70,80.90,...,222.45,192.10,236.80,3.10,30.05,0.85,14.40,6.65,0.65,2.40
Coburg,319.05,319.05,319.05,319.05,319.05,319.05,319.05,319.05,319.05,80.55,...,230.75,202.30,238.50,2.85,24.00,11.10,11.30,1.95,0.35,1.60
Deggendorf,320.15,320.15,320.15,320.15,320.15,320.15,320.15,320.15,320.15,83.20,...,220.65,187.30,236.95,2.50,32.90,1.95,15.40,8.05,2.05,1.35
Erlangen,319.05,319.05,319.05,319.05,319.05,319.05,319.05,319.05,319.05,75.10,...,234.50,185.85,243.95,2.85,17.80,4.05,12.60,3.20,0.30,1.30
Eschenbach,318.55,318.55,318.55,318.55,318.55,318.55,318.55,318.55,318.55,82.70,...,228.65,197.90,235.85,3.10,19.50,8.85,10.65,2.80,0.55,1.85
Grafenwöhr,320.65,320.65,320.65,320.65,320.65,320.65,320.65,320.65,320.65,83.15,...,230.60,199.25,237.50,3.10,19.35,6.25,10.80,2.55,0.55,1.90
Hof,319.85,319.85,319.85,319.85,319.85,319.85,319.85,319.85,319.85,65.95,...,244.30,211.70,253.90,1.80,21.70,4.05,12.95,2.35,0.35,1.60
Ingolstadt,318.70,318.70,318.70,318.70,318.70,318.70,318.70,318.70,318.70,68.90,...,232.95,195.40,249.80,2.20,31.60,5.65,15.40,7.95,1.55,2.35
Kemnath,318.85,318.85,318.85,318.85,318.85,318.85,318.85,318.85,318.85,80.05,...,232.15,203.80,238.80,2.90,19.65,6.20,9.55,2.80,0.65,1.85
Kempten,319.20,319.20,319.20,319.20,319.20,319.20,319.20,319.20,319.20,81.70,...,229.70,191.20,237.50,2.25,16.60,9.90,12.50,1.45,0.35,1.10
Landshut,320.20,320.20,320.20,320.20,320.20,320.20,320.20,320.20,320.20,80.85,...,233.60,200.50,239.35,2.55,24.35,9.20,11.05,2.10,0.55,1.85
München,320.50,320.50,320.50,320.50,320.50,320.50,320.50,320.50,320.50,80.55,...,232.10,188.50,239.95,1.65,31.05,9.75,11.60,2.40,1.00,0.80
Nabburg,318.70,318.70,318.70,318.70,318.70,318.70,318.70,318.70,318.70,80.20,...,232.70,203.20,238.50,3.10,19.80,6.20,9.55,2.75,0.65,1.75
Neu-Ulm,320.70,320.70,320.70,320.70,320.70,320.70,320.70,320.70,320.70,82.60,...,228.05,193.05,238.10,2.30,27.50,7.60,13.45,2.35,0.80,1.05
Neumarkt,317.80,317.80,317.80,317.80,317.80,317.80,317.80,317.80,317.80,86.95,...,211.45,182.10,230.85,2.70,33.25,1.05,15.75,6.30,1.75,1.10
Neunburg,319.05,319.05,319.05,319.05,319.05,319.05,319.05,319.05,319.05,82.25,...,227.20,199.30,236.80,1.85,25.65,6.10,12.30,3.55,0.95,2.40
Neustadt,319.45,319.45,319.45,319.45,319.45,319.45,319.45,319.45,319.45,80.55,...,232.25,203.65,238.90,3.05,19.65,6.20,9.50,2.80,0.65,1.85
Nürnberg,320.30,320.30,320.30,320.30,320.30,320.30,320.30,320.30,320.30,62.60,...,248.80,212.90,257.70,2.00,24.70,0.40,8.80,3.05,0.40,2.30
Oberviechtach,319.60,319.60,319.60,319.60,319.60,319.60,319.60,319.60,319.60,82.75,...,230.40,198.45,236.85,3.10,19.60,6.20,10.70,2.80,0.65,1.75
Parsberg,320.20,320.20,320.20,320.20,320.20,320.20,320.20,320.20,320.20,83.10,...,230.45,199.15,237.10,3.05,19.95,8.95,10.85,2.55,0.65,1.90
Passau,320.60,320.60,320.60,320.60,320.60,320.60,320.60,320.60,320.60,84.15,...,226.60,190.70,236.45,2.95,31.65,9.10,14.30,2.75,1.40,2.10
Regensburg,319.35,319.35,319.35,319.35,319.35,319.35,319.35,319.35,319.35,77.55,...,233.90,206.25,241.80,2.00,25.40,4.00,12.15,3.00,0.45,0.85
Riedenburg,319.55,319.55,319.55,319.55,319.55,319.55,319.55,319.55,319.55,83.05,...,230.15,197.05,236.50,3.00,19.70,6.20,10.80,2.55,0.65,1.85
Roding,320.35,320.35,320.35,320.35,320.35,320.35,320.35,320.35,320.35,83.15,...,231.10,199.15,237.20,3.10,20.10,6.60,10.85,2.55,0.65,1.85
Rosenheim,320.60,320.60,320.60,320.60,320.60,320.60,320.60,320.60,320.60,82.35,...,231.10,202.65,238.25,2.25,25.50,10.05,12.35,2.05,0.70,1.65
Schwandorf,320.30,320.30,320.30,320.30,320.30,320.30,320.30,320.30,320.30,78.60,...,236.00,203.65,241.70,1.70,18.35,7.10,8.50,2.85,0.60,1.70
Sulzbach-Rosenberg,317.30,317.30,317.30,317.30,317.30,317.30,317.30,317.30,317.30,84.40,...,223.10,188.15,232.90,2.55,29.25,9.50,13.30,4.30,1.15,2.20
Tirschenreuth,317.30,317.30,317.30,317.30,317.30,317.30,317.30,317.30,317.30,79.80,...,227.75,193.70,237.50,2.60,17.45,2.10,10.90,1.70,0.80,0.85
Vohenstrauß,319.65,319.65,319.65,319.65,319.65,319.65,319.65,319.65,319.65,82.95,...,229.85,198.35,236.70,3.05,19.35,6.25,10.80,2.55,0.55,1.80
Waldmünchen,320.65,320.65,320.65,320.65,320.65,320.65,320.65,320.65,320.65,71.65,...,240.50,198.70,249.00,1.65,12.95,6.60,6.15,6.35,0.40,2.35
Weiden,318.50,318.50,318.50,318.50,318.50,318.50,318.50,318.50,318.50,92.30,...,198.35,169.10,226.20,1.75,10.25,2.75,13.25,15.35,0.45,2.00
Würzburg,320.70,320.70,320.70,320.70,320.70,320.70,320.70,320.70,320.70,70.45,...,241.70,212.40,250.25,2.10,21.75,4.10,11.80,2.45,0.40,1.85

**Wie viele verschiedene Anbieter haben insgesamt Tarife angeboten?**

In [10]:
print(len(final_df['Anbieter'].unique()))

78

**d)  Ermitteln Sie, welche unterschiedlichen Tarife in Amberg angeboten wurden**

In [11]:
amberg_tarif=pd.Series(final_df[final_df['Stadt']=='Amberg']['Tarif'].unique(), name='Tarif')
amberg_tarif

0                                   Tarif Fairpower one
1                               Tarif Dynamischer Tarif
2                             Tarif ÖkoStrom Komfort 12
3     Marke der Rheinische Elektrizitäts- und Gasver...
4                       Tarif ELEKTRIZITÄT BERLIN Strom
                            ...
72                                 Tarif Q.ENERGY Eco12
73                              Tarif MONTANA garant 12
74                             Tarif Select+ Comfort 18
75    Marke der rhenag Rheinische Energie AG\n      ...
76                           Tarif Naturstrom Premium18
Name: Tarif, Length: 77, dtype: object